services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    working_dir: /usr/src/CSFD/frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/CSFD/frontend
      - /usr/src/CSFD/frontend/node_modules
    command: sh -c "pnpm run dev --host"
    depends_on:
      - backend

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    working_dir: /usr/src/CSFD/backend
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - ./backend:/usr/src/CSFD/backend
      - /usr/src/CSFD/backend/node_modules
    command: sh -c "npx prisma generate && pnpm run dev"
    depends_on:
      - postgres

  postgres:
    image: postgres:16.3
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
