name: autofix.ci

on:
  pull_request:
  push:

permissions: {}

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies and run formatter
        run: |
          pnpm install --frozen-lockfile
          pnpm run format

      - uses: autofix-ci/action@v1
        with:
          commit-message: 'style: apply Prettier format'
